#!/bin/bash

PACK_NAME="Visual Studio Code"
PACK_CONTENT="VSCode Last version"

pack-setup(){
    echo "Installing $PACK_NAME..."
    
    # Get credentials and gpg files
    wget -qO- https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > packages.microsoft.gpg
    sudo install -D -o root -g root -m 644 packages.microsoft.gpg /etc/apt/keyrings/packages.microsoft.gpg
    sudo sh -c 'echo "deb [arch=amd64,arm64,armhf signed-by=/etc/apt/keyrings/packages.microsoft.gpg] https://packages.microsoft.com/repos/code stable main" > /etc/apt/sources.list.d/vscode.list'
    rm -f packages.microsoft.gpg

    # Install VSCode
    sudo nala update
    sudo nala install -y code

    echo "$PACK_NAME installed sucessfully."
}
